import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToasterContext from './context/ToasterContext'
import ModalContext from './context/ModalContext'
import getCurrentUser from './actions/getCurrentUser'
import { NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

  

export default async function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode
  params: any
}) {
  let messages;
  
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  const currentUser = await getCurrentUser();


  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ToasterContext/>
          <ModalContext currentUser={currentUser}/>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}

